app:
    resource: "@AppBundle/Controller/RationalController.php"
    type:     annotation
    prefix :  rational

app1:
    resource: "@AppBundle/Controller/CalculatorController.php"
    type:     annotation
    prefix:   calculator

default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:      annotation